Main
dlang/stdcpp pull request #3
Opened 2023-10-15 08:35 UTC by Emmankoko

2023-10-16 07:32 UTC, Geod24 requested changes
Made a few comments. Also make sure to include a proper title / commit message in the future.

2023-10-16 07:32 UTC, Geod24 commented on source/stdcpp/vector.d
> +	if(__traits(isArithmetic, T))
This might need to be `static if`. Since the condition is always known at compiler time.

2023-10-16 07:32 UTC, Geod24 commented on source/stdcpp/vector.d
> +	}
Please configure your editor to automatically indent by 4 spaces.

2023-10-16 07:32 UTC, Geod24 commented on source/stdcpp/vector.d
> +*********************************************************************/
Can you show me the mangling issue ?

2023-10-16 07:32 UTC, Geod24 commented on source/stdcpp/vector.d
> +	this()(size_t __n)
Note that this constructor is templated, something that is not possible in C++. So this does not mangle to the constructor as it should.
Try compiling the following:
```C++
#include <vector>

int main ()
{
    std::vector<int> vec;
    return 0;
}
```

And then `nm a.out`, you'll get the following (removed irrelevant output):
```
0000000000001481 W _ZNSt12_Destroy_auxILb1EE9__destroyIPiEEvT_S3_
000000000000121e W _ZNSt12_Vector_baseIiSaIiEE12_Vector_implC1Ev
000000000000121e W _ZNSt12_Vector_baseIiSaIiEE12_Vector_implC2Ev
00000000000011be W _ZNSt12_Vector_baseIiSaIiEE12_Vector_implD1Ev
00000000000011be W _ZNSt12_Vector_baseIiSaIiEE12_Vector_implD2Ev
0000000000001366 W _ZNSt12_Vector_baseIiSaIiEE13_M_deallocateEPim
0000000000001324 W _ZNSt12_Vector_baseIiSaIiEE17_Vector_impl_dataC1Ev
0000000000001324 W _ZNSt12_Vector_baseIiSaIiEE17_Vector_impl_dataC2Ev
00000000000013a0 W _ZNSt12_Vector_baseIiSaIiEE19_M_get_Tp_allocatorEv
00000000000011de W _ZNSt12_Vector_baseIiSaIiEEC1Ev
00000000000011de W _ZNSt12_Vector_baseIiSaIiEEC2Ev
000000000000126a W _ZNSt12_Vector_baseIiSaIiEED1Ev
000000000000126a W _ZNSt12_Vector_baseIiSaIiEED2Ev
00000000000013ef W _ZNSt16allocator_traitsISaIiEE10deallocateERS0_Pim
00000000000011fe W _ZNSt6vectorIiSaIiEEC1Ev
00000000000011fe W _ZNSt6vectorIiSaIiEEC2Ev
00000000000012bc W _ZNSt6vectorIiSaIiEED1Ev
00000000000012bc W _ZNSt6vectorIiSaIiEED2Ev
0000000000001421 W _ZSt8_DestroyIPiEvT_S1_
00000000000013b2 W _ZSt8_DestroyIPiiEvT_S1_RSaIT0_E
```

If you run c++filt on this:
```
0000000000001481 W void std::_Destroy_aux<true>::__destroy<int*>(int*, int*)
000000000000121e W std::_Vector_base<int, std::allocator<int> >::_Vector_impl::_Vector_impl()
000000000000121e W std::_Vector_base<int, std::allocator<int> >::_Vector_impl::_Vector_impl()
00000000000011be W std::_Vector_base<int, std::allocator<int> >::_Vector_impl::~_Vector_impl()
00000000000011be W std::_Vector_base<int, std::allocator<int> >::_Vector_impl::~_Vector_impl()
0000000000001366 W std::_Vector_base<int, std::allocator<int> >::_M_deallocate(int*, unsigned long)
0000000000001324 W std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data::_Vector_impl_data()
0000000000001324 W std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data::_Vector_impl_data()
00000000000013a0 W std::_Vector_base<int, std::allocator<int> >::_M_get_Tp_allocator()
00000000000011de W std::_Vector_base<int, std::allocator<int> >::_Vector_base()
00000000000011de W std::_Vector_base<int, std::allocator<int> >::_Vector_base()
000000000000126a W std::_Vector_base<int, std::allocator<int> >::~_Vector_base()
000000000000126a W std::_Vector_base<int, std::allocator<int> >::~_Vector_base()
00000000000013ef W std::allocator_traits<std::allocator<int> >::deallocate(std::allocator<int>&, int*, unsigned long)
00000000000011fe W std::vector<int, std::allocator<int> >::vector()
00000000000011fe W std::vector<int, std::allocator<int> >::vector()
00000000000012bc W std::vector<int, std::allocator<int> >::~vector()
00000000000012bc W std::vector<int, std::allocator<int> >::~vector()
0000000000001421 W void std::_Destroy<int*>(int*, int*)
00000000000013b2 W void std::_Destroy<int*, int>(int*, int*, std::allocator<int>&)
```

So as you can see , the C++ template emits the ctor, you just have to bind it.

2023-10-20 23:59 UTC, Geod24 commented
@Emmankoko : This is what you are missing:
https://github.com/dlang/stdcpp/commit/9c780ac69a495efdbe22ebf802d1112f7af9e794
Do a `git fetch` and then `git cherry-pick 9c780ac` on your branch to import it.

2023-10-24 11:52 UTC, Geod24 commented on source/stdcpp/test/vector.d
> +allocator!int alloc_instance = allocator!(int).init;
We need to remove this. I think a D constructor that forwards to the C++ constructor makes sense.

2023-10-24 11:52 UTC, Geod24 commented on source/stdcpp/test/vector.d
> +int b = 9;
Remove or move to unittest scope

2023-10-24 11:53 UTC, Geod24 commented on source/stdcpp/test/vector.d
> +    vec.push_back(a);
We need to accept rvalue

2023-10-24 12:16 UTC, Geod24 commented on source/stdcpp/vector.d
> -        insert(0, array);
```D
version (CppRuntime_Microsoft)
    insert(0, array);
else
    // Do something else
```

2023-10-24 22:24 UTC, Emmankoko commented on source/stdcpp/test/vector.d
> +    vec.push_back(a);
got it working now

2023-10-25 18:18 UTC, Emmankoko commented on source/stdcpp/test/vector.d
> +int b = 9;
removed

2023-12-19 13:04 UTC, Geod24 commented on source/stdcpp/string.d
> +// I think we can have these here now, since the project have been moved from druntime
Just replace the comment with `///` (so that it ends up in documentation)

2023-12-19 13:04 UTC, Geod24 commented on .github/workflows/e2e.yml
> +       #Use this branch name in your fork to test changes
Debugging artifacts

2023-12-19 13:04 UTC, Geod24 commented on dub.json
> +            "sourceFiles": [ "extras/*.o" ]
Only works for clang, we need a way to test both clang++ and g++.

Ideas:
- A configuration that is `unittest-clang` and one `unittest-gcc` but then try to have a sane default.

2023-12-19 13:04 UTC, Geod24 commented on source/stdcpp/list.d
> +version(CppRuntime_Gcc)
https://dlang.org/dstyle.html

2023-12-19 13:04 UTC, Geod24 commented on source/stdcpp/list.d
> +enum def {value}; //for later use
Can't call C++ default constructor from D when doing this:
```
list!int my_list;
```

Options:
`@disable this() @safe pure nothrow @nogc scope;`

But also defining a constructor hides the default constructor.

Can do:

`static list make ();`

2023-12-19 13:04 UTC, Geod24 commented on source/stdcpp/list.d
> +	@disable this();
Attributes

2023-12-19 13:04 UTC, Geod24 commented on source/stdcpp/list.d
> +//			~this();
Clean any artifacts

2024-02-05 12:05 UTC, Geod24 commented
Did a few adjustments and moved to #6

2024-02-05 12:05 UTC, closed without merging